version: '3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"


  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A main worker -l info
    depends_on:
      - redis
