# Generated by Django 3.2 on 2023-04-10 21:00

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='pp',
            field=models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_images_to_profile),
        ),
    ]
